# Memoria del demonio de Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Compilación en paralelo de los módulos
org.gradle.parallel=true

# Usar AndroidX en lugar de las librerías de soporte antiguas
android.useAndroidX=true

# Generar únicamente los recursos realmente utilizados
android.nonTransitiveRClass=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
